routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('posts','PostsController');

Auth::routes();

Route::get('/dashboard', 'DashboardController@index');
Route::get('/','PostsController@index');

Route::post('/posts/{postID}/comments','CommentController@store');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
	protected $fillable = [
    'body',
    'user_id'
   ];

    public function post()
    {
    	return $this->belongsTo(Post::class);
    }


    public function user()
    {
    	return $this->belongsTo('App\User');
    }
}

app/Dashboard.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dashboard extends Model
{
    //

    public function post(){
    	return $this->hasMany('App\Post');
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
	//Table Name
    // protected $table = 'posts';

    // //Primary Key
    // public $primaryKey = 'id';

    // //Time Stamp
    // public $timestamps = true;

    protected $fillable = [
    'title',
    'body',
    'user_id'
   ];

    public function user()
    {
    	return $this->belongsTo('App\User');
    }


    public function comments()
    {
        return $this->hasMany('App\Comment');
    }


    public function dashboard()

    {
        return $this->belongsTo('App\Dashboard');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function posts(){
        return $this->hasMany('App\Post');
    }

    public function comments(){
        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\User;
use  App\Post;

use App\Comment;

use App\Http\Requests\CommentFormRequest;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CommentFormRequest $request, $postID)
    {

        $post = Post::findOrFail($postID);
        
        $post->comments()->create([
            'body' => $request->comment,
            'user_id' => auth()->user()->id
        ]);

        // Comment::create([
        //     'body' => $request->comment,
        //     'post_id' => $postID,
        //     'user_id' => auth()->user()->id
        // ]);

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\User;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('dashboard')->with('posts', auth()->user()->posts);
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Post;

use App\Http\Requests\PostFormRequest;
//use Illuminate\Http\Request;


class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts =  Post::orderBy('id','desc')->paginate(10);

        return view('posts.index')->with('posts', $posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostFormRequest $request)
    {
    
        Post::Create([
            'title' => $request->title,
            'body' => $request->body,
            'user_id' =>auth()->user()->id
        ]);
        return redirect(route('posts.index'))->with('success', 'Post Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::find($id);

        return view('posts.show')->with('post', $post);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <a href="{{ route('posts.create') }}" class="btn btn-primary"><i class="fa fa-pencil"></i> Create Post</a>
                   <h1>My Posts</h1>
                        @if(filled($posts))
                    <table class="table table-striped">
                        <thead>
                            <th>Title</th>
                            <th></th>
                            <th></th>
                        </thead>

                        <tbody>
                            @foreach($posts as $post)

                            <tr>
                                <td>{{ $post->title }}</td>
                                <td><a href="/posts/{{ $post->id }}/edit" class="btn btn-primary"><i class="fa fa-edit"></i> Edit</a></td>
                                <td><a href="" class="btn btn-danger"><i class="fa fa-trash-o"></i> Delete</a></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                    @else
                    <h3>You Have No Post</h3>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                  <i class="fa fa-home"></i>
                    {{ config('app.name', 'Bakale Blog') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}"><i class="fa fa-sign-in"></i> {{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}"><i class="fa fa-edit"></i> {{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="/dashboard"><i class="fa fa-dashboard"></i> Dashboard</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"> <i class="fa fa-power-off"></i>
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
            <h2>Make A New Post</h2>
              <hr>
               <form action="{{ route('posts.store') }}" method="POST">
                 @csrf
                 <div class="col-md-12">
                   Title
                   <input type="text" name="title" class="form-control">
                 </div>
                  <div class="col-md-12">
                   Post Body
                   <textarea name="body" id="" cols="30" rows="10" class="form-control"></textarea>
                 </div>
                  <div class="col-md-6">
                   <br>
                  <button type="submit" name="submit" class="btn btn-success">Submit</button>
                 </div>
               </form>              
        </div>
  @endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
             @guest
                    @if (Route::has('register'))
                       
                    @endif
                @else
                   <a href="{{ route('posts.create') }}" class="btn btn-primary"><i class="fa fa-pencil"></i> Create A Post</a>
                    <br>
                   <br>
                @endguest
            
                    @if(filled($posts))
                      
                      @foreach($posts as $key => $post)
                        <div class="col-md-12">
                          <div class="card border-success mb-3">
                            <div class="card-header bg-transparent border-success"><h1>{{ $post->title }}</h1></div>
                            <div class="card-body text-success">
                               <img src="{{ asset('images/blog.png') }}" alt="post img" class="img-thumbnail float-left">
                              <p class="card-text text-justify">{{ $post->body }}</p>
                            </div>
                            <div class="card-footer bg-transparent border-success">Posted On <i class="fa fa-clock-o"></i> {{ $post->created_at->diffForHumans()}} By {{ $post->user->name }} <a href="/posts/{{ $post->id }}" class="btn btn-success pull-right">Read More</a> </div>
                          </div>
                        </div>   
                       

                      @endforeach

                    @endif


    </div>
  @endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
             @guest
                    @if (Route::has('register'))
                       
                    @endif
                @else
                   <a href="{{ route('posts.create') }}" class="btn btn-primary"><i class="fa fa-pencil"></i> Create A Post</a>
                   <br>
                   <br>
                @endguest

                        <div class="col-md-12">
                          <div class="card border-success mb-3">
                            <div class="card-header bg-transparent border-success"><h1>{{ $post->title }}</h1></div>
                            <div class="card-body text-success">
                               <img src="{{ asset('images/blog.png') }}" alt="post img" class="img-thumbnail float-left">
                              <p class="card-text text-justify">{{ $post->body }}</p>
                            </div>
                            <div class="card-footer bg-transparent border-success">Posted On <i class="fa fa-clock-o"></i> {{ $post->created_at->diffForHumans()}} By {{ $post->user->name }} </div>
                          </div>
                          <hr>

                          <div class="card border-success mb-3">
                            <div class="card-header bg-transparent border-success"><h1><i class="fa fa-comments"></i> Comments</h1></div>
                            <div class="card-body text-success">
                              <ul class="list-group">
                              @foreach($post->comments as $comment)
                                <strong>{{ $comment->user->name }}:   <span class="pull-right"><i class="fa fa-clock-o"> {{ $comment->created_at->diffForHumans() }}</i></span></strong>

                                  <li class="list-group-item">
                                    {{ $comment->body }}
                                  </li>

                              @endforeach
                            </ul>
                            </div>
                            <div class="card-footer bg-transparent border-success">
                              @guest
                                     @if (Route::has('register'))
                                        
                                     @endif
                                 @else
                                   <form action="\posts\{{$post->id }}\comments" method="POST">
                                    @csrf
                                    <div class="col-md-12">
                                      Type Your Comment
                                      <textarea name="comment" id="" cols="30" rows="10" class="form-control"></textarea>
                                    </div>
                                    <div class="col-md-6">
                                      <br>
                                      <button type="submit" name="submit" class="btn btn-success">Submit</button>
                                    </div>
                                  </form>
                                 @endguest
                            </div>
                          </div>

                        </div>   

    </div>
  @endsection